name: playpenHtml
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  http: any
  pappes_web_utility:
    path: ../../../aarvark/dart/pappes_web_utility
