name: its_all_about_you
description: A sample application
dependencies:
  polymer: '>=0.15.1 <0.17.0'
transformers:
- polymer:
    entry_points:
      - web/index.html
    inline_stylesheets:
       web/its_all_about_you.css: false
