name: pappesBookmarklet
description: A sample web application
dependencies:
  browser: any
  pappes_utility:
    path: ../../../../aarvark/dart/pappes_utility
  pappes_web_utility:
    path: ../../../../aarvark/dart/pappes_web_utility
